name: Format Java Code

on:
  push:
    branches: [ main ]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # required for committing

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: "--skip-sorting-imports --replace src/**/*.java"

      # - name: Commit and Push Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Auto-format Java code"
      #     branch: main
